name: Despliegue Producción

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Conectar al VPS y desplegar
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            set -e  # Salir ante cualquier error
            echo "=== Creando estructura de directorios ==="
            sudo mkdir -p /var/www/fuente_natura
            sudo chown -R $USER:$USER /var/www/fuente_natura
            sudo chmod -R 755 /var/www

            echo "=== Clonando/Actualizando repositorio ==="
            cd /var/www/fuente_natura
            if [ ! -d .git ]; then
              git clone https://github.com/UnCubanoDev/fuente-natura.git .
            else
              git reset --hard HEAD
              git pull origin master
            fi

            echo "=== Instalando dependencias ==="
            pnpm install --frozen-lockfile
            pnpm run build

            echo "=== Gestionando aplicación PM2 ==="
            if pm2 id fuentenatura > /dev/null; then
              pm2 reload fuentenatura --update-env
            else
              pm2 start "pnpm start" --name fuentenatura
            fi
            pm2 save
            pm2 startup 2>/dev/null

            echo "=== Reiniciando Nginx ==="
            sudo nginx -t
            sudo systemctl restart nginx

            echo "=== Despliegue completado ==="
